name: weightloss
favicon: null
layout_spectrum: 0.6401813311967999
typography_spectrum: 0.3976571711245924
title: Practical tips from how I burned over 100 lbs of fat and make more than 20 lbs of muscle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#111715'
    - '#51524d'
    - '#be8f7d'
    - '#b05f4a'
  brandStrength: 0.31133317667990923
  lightness: 0.6342365154996514
  saturation: 0.6214462120551616
  rhythmicContrast: 0.569118415703997
purpose: []
